[templates."Redmi 2A"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "HM 2A"
device = "lte26007"
product = "lte26007"
fingerprint = ""
name = "lte26007"
marketname = "Redmi 2A"
author = "GitHub@Z-fly"
