[templates."Redmi Note 14 5G"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "24094RAD4C"
device = "beryl"
product = "beryl"
fingerprint = ""
name = "beryl"
marketname = "Redmi Note 14 5G"
author = "GitHub@JokerQi666"
