[templates."REDMI Note 15 Pro"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "25080RABDC"
device = "lapis"
product = "lapis"
fingerprint = ""
name = "lapis"
marketname = "REDMI Note 15 Pro"
author = "GitHub@JokerQi666"
