[templates."REDMI Turbo 4 Pro"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "25053RT47C"
device = "onyx"
product = "onyx"
fingerprint = ""
name = "onyx"
marketname = "REDMI Turbo 4 Pro"
author = "GitHub@JokerQi666"
