[templates."REDMI Turbo 4"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "24129RT7CC"
device = "rodin"
product = "rodin"
fingerprint = ""
name = "rodin"
marketname = "REDMI Turbo 4"
author = "GitHub@JokerQi666"
