[templates."Redmi K60"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "23013RK75C"
device = "mondrian"
product = "mondrian"
fingerprint = ""
name = "mondrian"
marketname = "Redmi K60"
author = "GitHub@JokerQi666"
