[templates."REDMI Note 7"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "M1901F7E"
device = "lavender"
product = "lavender"
fingerprint = ""
name = "lavender"
marketname = "Redmi Note 7"
author = "GitHub@Z-fly"
