[templates."REDMI K80 Pro"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "24122RKC7C"
device = "miro"
product = "miro"
fingerprint = ""
name = "miro"
marketname = "REDMI K80 Pro"
author = "GitHub@JokerQi666"

