[templates."Redmi Note 14 Pro"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "24090RA29C"
device = "malachite"
product = "malachite"
fingerprint = ""
name = "malachite"
marketname = "Redmi Note 14 Pro"
author = "GitHub@JokerQi666"
