[templates."Redmi K70 Pro"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "23117RK66C"
device = "manet"
product = "manet"
fingerprint = ""
name = "manet"
marketname = "Redmi K70 Pro"
author = "GitHub@JokerQi666"
