[templates."REDMI K100 Pro"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "M511CD"
device = "athens"
product = "athens"
fingerprint = ""
name = "athens"
marketname = "REDMI K100 Pro"
author = "GitHub@JokerQi666"