[templates."Redmi K70 Ultra"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "2407FRK8EC"
device = "rothko"
product = "rothko"
fingerprint = ""
name = "rothko"
marketname = "Redmi K70 Ultra"
author = "GitHub@JokerQi666"
