[templates."REDMI R70 5G"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "26020RN1AC"
device = "somalia"
product = "somalia"
fingerprint = ""
name = "somalia"
marketname = "REDMI R70 5G"
author = "GitHub@Z-fly"
