[templates."Redmi K50 Ultra"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "22081212C"
device = "diting"
product = "diting"
fingerprint = ""
name = "diting"
marketname = "Redmi K50 Ultra"
author = "GitHub@JokerQi666"
