[templates."REDMI Note 15"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "25098RA98C"
device = "kunzite"
product = "kunzite"
fingerprint = ""
name = "kunzite"
marketname = "REDMI Note 15"
author = "GitHub@JokerQi666"
