[templates."Redmi Note 13 5G"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "2312DRAABC"
device = "gold"
product = "gold"
fingerprint = ""
name = "gold"
marketname = "Redmi Note 13 5G"
author = "GitHub@JokerQi666"
