[templates."REDMI A7 Pro 5G"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "26020RN1AI"
device = "somalia"
product = "somalia"
fingerprint = ""
name = "somalia"
marketname = "REDMI A7 Pro 5G"
author = "GitHub@Z-fly"
