[templates."Redmi Turbo 3"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "24069RA21C"
device = "peridot"
product = "peridot"
fingerprint = ""
name = "peridot"
marketname = "Redmi Turbo 3"
author = "GitHub@JokerQi666"
