[templates."Redmi K60 Ultra"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "23078RKD5C"
device = "corot"
product = "corot"
fingerprint = ""
name = "corot"
marketname = "Redmi K60 Ultra"
author = "GitHub@JokerQi666"
