[templates."REDMI Note 1S"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "HM NOTE 1S"
device = "gucci"
product = "gucci"
fingerprint = ""
name = "gucci"
marketname = "Redmi Note 1S"
author = "GitHub@Z-fly"
