[templates."REDMI K80"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "24117RK2CC"
device = "zorn"
product = "zorn"
fingerprint = ""
name = "zorn"
marketname = "REDMI K80"
author = "GitHub@JokerQi666"
