[templates."REDMI Note 4G"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "HM NOTE 1LTE"
device = "dior"
product = "dior"
fingerprint = ""
name = "dior"
marketname = "Redmi Note 4G"
author = "GitHub@Z-fly"
