[templates."REDMI K80 Ultra"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "25060RK16C"
device = "dali"
product = "dali"
fingerprint = ""
name = "dali"
marketname = "REDMI K80 Ultra"
author = "GitHub@JokerQi666"
