[templates."Redmi K70E"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "2311DRK48C"
device = "duchamp"
product = "duchamp"
fingerprint = ""
name = "duchamp"
marketname = "Redmi K70E"
author = "GitHub@JokerQi666"
