[templates."Redmi Note 13 Pro"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "2312CRAD3C"
device = "garnet"
product = "garnet"
fingerprint = ""
name = "garnet"
marketname = "Redmi Note 13 Pro"
author = "GitHub@JokerQi666"
