[templates."REDMI Note 17 Pro"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "2607DRA18C"
device = "iolite"
product = "iolite"
fingerprint = ""
name = "iolite"
marketname = "REDMI Note 17 Pro"
author = "GitHub@JokerQi666"
