[templates."REDMI K90 Max"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "2604FRK1EC"
device = "prague"
product = "prague"
fingerprint = ""
name = "prague"
marketname = "REDMI K90 Max"
author = "GitHub@JokerQi666"
