[templates."REDMI Note 17"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "26021RN18C"
device = "mist"
product = "mist"
fingerprint = ""
name = "mist"
marketname = "REDMI Note 17"
author = "GitHub@JokerQi666"
