[templates."REDMI K100 Pro Max"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "M098FE"
device = "songyuan"
product = "songyuan"
fingerprint = ""
name = "songyuan"
marketname = "REDMI K100 Pro Max"
author = "GitHub@JokerQi666"
