[templates."Redmi Note 13 Pro+"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "23090RA98C"
device = "zircon"
product = "zircon"
fingerprint = ""
name = "zircon"
marketname = "Redmi Note 13 Pro+"
author = "GitHub@JokerQi666"
