[templates."Redmi K70"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "23113RKC6C"
device = "vermeer"
product = "vermeer"
fingerprint = ""
name = "vermeer"
marketname = "Redmi K70"
author = "GitHub@JokerQi666"

