[templates."Redmi Note 12 Turbo"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "23049RAD8C"
device = "marble"
product = "marble"
fingerprint = ""
name = "marble"
marketname = "Redmi Note 12 Turbo"
author = "GitHub@JokerQi666"
