[templates."Redmi Note 14 Pro+"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "24115RA8EC"
device = "amethyst"
product = "amethyst"
fingerprint = ""
name = "amethyst"
marketname = "Redmi Note 14 Pro+"
author = "GitHub@JokerQi666"
