[templates."REDMI Turbo 5"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "2511FRT34C"
device = "klee"
product = "klee"
fingerprint = ""
name = "klee"
marketname = "REDMI Turbo 5"
author = "GitHub@JokerQi666"
