[templates."REDMI K90 Ultra"]
manufacturer = "Xiaomi"
brand = "REDMI"
model = "M332BF"
device = "warsaw"
product = "warsaw"
fingerprint = ""
name = "warsaw"
marketname = "REDMI K90 Ultra"
author = "GitHub@JokerQi666"
