[templates."Redmi K60 Pro"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "22127RK46C"
device = "socrates"
product = "socrates"
fingerprint = ""
name = "socrates"
marketname = "Redmi K60 Pro"
author = "GitHub@JokerQi666"
