[templates."Xiaomi MIX Fold 3"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2308CPXD0C"
device = "babylon"
product = "babylon"
fingerprint = ""
name = "babylon"
marketname = "Xiaomi MIX Fold 3"
author = "GitHub@JokerQi666"
