[templates."Xiaomi 11 Lite"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M2101K9C"
device = "renoir"
product = "renoir"
fingerprint = ""
name = "renoir"
marketname = "Xiaomi 11 Lite"
author = "GitHub@JokerQi666"
