[templates."Xiaomi MIX Flip"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2405CPX3DC"
device = "ruyi"
product = "ruyi"
fingerprint = ""
name = "ruyi"
marketname = "Xiaomi MIX Flip"
author = "GitHub@JokerQi666"
