[templates."Xiaomi Civi"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2109119BC"
device = "mona"
product = "mona"
fingerprint = ""
name = "mona"
marketname = "Xiaomi Civi"
author = "GitHub@JokerQi666"

