[templates."Xiaomi Civi 5 Pro"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "25067PYE3C"
device = "luming"
product = "luming"
fingerprint = ""
name = "luming"
marketname = "Xiaomi Civi 5 Pro"
author = "GitHub@JokerQi666"
