[templates."Xiaomi 4 LTE"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "MI 4LTE"
device = "cancro"
product = "cancro"
fingerprint = ""
name = "cancro"
marketname = "Xiaomi 4 LTE"
author = "GitHub@Z-fly"
