[templates." Xiaomi MIX FOLD"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M2011J18C"
device = "cetus"
product = "cetus"
fingerprint = ""
name = "cetus"
marketname = " Xiaomi MIX FOLD"
author = "GitHub@JokerQi666"
