[templates."Xiaomi Civi 3"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "23046PNC9C"
device = "yuechu"
product = "yuechu"
fingerprint = ""
name = "yuechu"
marketname = "Xiaomi Civi 3"
author = "GitHub@JokerQi666"


