[templates."Xiaomi 11 Pro"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M2102K1AC"
device = "mars"
product = "mars"
fingerprint = ""
name = "mars"
marketname = "Xiaomi 11 Pro"
author = "GitHub@JokerQi666"
