[templates."Xiaomi 10S"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M2102J2SC"
device = "thyme"
product = "thyme"
fingerprint = ""
name = "thyme"
marketname = "Xiaomi 10S"
author = "GitHub@JokerQi666"
