[templates."Xiaomi 10 Ultra"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M2007J1SC"
device = "cas"
product = "cas"
fingerprint = ""
name = "cas"
marketname = "Xiaomi 10 Ultra"
author = "GitHub@JokerQi666"
