[templates."Xiaomi Civi 1S"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2109119BC"
device = "zijin"
product = "zijin"
fingerprint = ""
name = "zijin"
marketname = "Xiaomi Civi 1S"
author = "GitHub@JokerQi666"

