[templates."Xiaomi 12S"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2206123SC"
device = "mayfly"
product = "mayfly"
fingerprint = ""
name = "mayfly"
marketname = "Xiaomi 12S"
author = "GitHub@JokerQi666"
