[templates."Xiaomi 4i"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "Mi 4i"
device = "ferrari"
product = "ferrari"
fingerprint = ""
name = "ferrari"
marketname = "Xiaomi 4i"
author = "GitHub@Z-fly"
