[templates."Xiaomi 18 Fold"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2608BPX34C"
device = "lhasa"
product = "lhasa"
name = "lhasa"
marketname = "Xiaomi 18 Fold"
fingerprint = ""
author = "GitHub@JokerQi666"
