[templates."Xiaomi 17 Ultra By Leica"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "25128PNA1C"
device = "nezha"
product = "nezha"
fingerprint = ""
name = "nezha"
marketname = "Xiaomi 17 Ultra by Leica"
author = "GitHub@oTnTo233"
