[templates."Xiaomi MIX Fold 2"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "22061218C"
device = "zizhan"
product = "zizhan"
fingerprint = ""
name = "zizhan"
marketname = "Xiaomi MIX Fold 2"
author = "GitHub@JokerQi666"
