[templates."Xiaomi 11 Ultra"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M2102K1C"
device = "star"
product = "star"
fingerprint = ""
name = "star"
marketname = "Xiaomi 11 Ultra"
author = "GitHub@JokerQi666"

