[templates."Xiaomi 17 Max"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2605EPN8EC"
device = "byron"
product = "byron"
fingerprint = ""
name = "byron"
marketname = "Xiaomi 17 Max"
author = "GitHub@JokerQi666"
