[templates."Xiaomi 10 Lite"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M2002J9E"
device = "vangogh"
product = "vangogh"
fingerprint = ""
name = "vangogh"
marketname = "Xiaomi 10 Lite"
author = "GitHub@JokerQi666"
