[templates."Xiaomi 12 Pro"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2201122C"
device = "zeus"
product = "zeus"
fingerprint = ""
name = "zeus"
marketname = "Xiaomi 12 Pro"
author = "GitHub@JokerQi666"
