[templates."Xiaomi MIX Flip 2"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2505APX7BC"
device = "bixi"
product = "bixi"
fingerprint = ""
name = "bixi"
marketname = "Xiaomi MIX Flip 2"
author = "GitHub@JokerQi666"
