[templates."Xiaomi 12S Pro"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2206122SC"
device = "unicorn"
product = "unicorn"
fingerprint = ""
name = "unicorn"
marketname = "Xiaomi 12S Pro"
author = "GitHub@JokerQi666"

