[templates."Xiaomi Civi 2"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2209129SC"
device = "ziyi"
product = "ziyi"
fingerprint = ""
name = "ziyi"
marketname = "Xiaomi Civi 2"
author = "GitHub@JokerQi666"
