[templates."Xiaomi 12 Pro 天玑版"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2207122MC"
device = "daumier"
product = "daumier"
fingerprint = ""
name = "daumier"
marketname = "Xiaomi 12 Pro 天玑版"
author = "GitHub@JokerQi666"
