[templates."Xiaomi 12"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2201123C"
device = "cupid"
product = "cupid"
fingerprint = ""
name = "cupid"
marketname = "Xiaomi 12"
author = "GitHub@JokerQi666"
