[templates."Xiaomi 11"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M2011K2C"
device = "venus"
product = "venus"
fingerprint = ""
name = "venus"
marketname = "Xiaomi 11"
author = "GitHub@JokerQi666"
