[templates."Xiaomi MIX Fold 4"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "24072PX77C"
device = "goku"
product = "goku"
fingerprint = ""
name = "goku"
marketname = "Xiaomi MIX Fold 4"
author = "GitHub@JokerQi666"
