[templates."Xiaomi 17T Pro"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "M025EC"
device = "warhol"
product = "warhol"
fingerprint = ""
name = "warhol"
marketname = "Xiaomi 17T Pro"
author = "GitHub@JokerQi666"
