[templates."Xiaomi Civi 4 Pro"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "24053PY09C"
device = "chenfeng"
product = "chenfeng"
fingerprint = ""
name = "chenfeng"
marketname = "Xiaomi Civi 4 Pro"
author = "GitHub@JokerQi666"
