[templates.iqoo_15_ultra]
manufacturer = "vivo"
brand = "vivo"
model = "V2546A"
device = "V2546A"
product = "V2546A"
fingerprint = "vivo/PD2546/PD2546:16/BP2A.250605.031.A3/compiler260228234011:user/release-keys"
name = "PD2546"
marketname = "VIVO iQOO 15 Ultra"
author = "GitHub@oTnTo233"
