[templates."OnePlus 15"]
manufacturer = "OnePlus"
brand = "OnePlus"
model = "PLK110"
device = "PLK110"
product = "PLK110"
fingerprint = ""
name = ""
marketname = "OnePlus 15"
author = "GitHub@oTnTo233"
description = "特点：部分游戏165帧"
